In [ ]:
#tao duong dan toi folder driver
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
#chuyen file qua folder moi
%cd '/content/gdrive/My Drive/Deep-learning'
! ls

In [10]:
#List
# phuong thuc pop()
x = []
for i in range(10):
  x.append(i)
tam = x.pop()
print(tam)
#slicing
x[2:4] = [8,9]
print(x) 

9
[0, 1, 8, 9, 4, 5, 6, 7, 8]


In [ ]:
#Dictionaries
#create
x = {"cat": "gruu","dog":3958} # mo hinh key:value
print(x["cat"])
x["fish"] ="wet" # them va khoi tao key: fish voi value: wet
print(x)
del x["cat"] #xoa key, value "cat" ra khoi dictionary.
#duyet theo key
for animal in x:
  print("A {} is {}".format(animal,x[animal]))
#duyet theo value
for i in x.values():
  print(i)
#duyet theo ca key va value
for animal, keys in x.items():
  past

In [ ]:
#library Numpy
import numpy as np
#create array in python
a= np.array([1,2,3])
# print(a.shape)
b= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # mang hai chieu
c= b[:2,1:3]
print(c)
b[0,1] =15
print(b)

In [ ]:
import numpy as np
arr1 = np.array([[1,2],[8,9]])
arr2 = np.array([[1,2],[2,2]])
# # tong
# print(arr1+arr2)
# print(np.add(arr1,arr2))
# # tru
# print(arr1 - arr2)
# print(np.subtract(arr1,arr2))
#nhan element-wise , nma la nhan tung phan tu voi tung vi tri giong nhau
# print(arr1*arr2)
# print(np.multiply(arr1,arr2))
# # chia element-wise(cach thuc giong nhu nhan element-wise)
# print(arr1/arr2)
# print(np.divide(arr1,arr2))
# # can bac hai
# print(np.sqrt(arr1))
# # nhan ma tran theo cach thong thuong
# print(arr1.dot(arr2))
# print(np.dot(arr1,arr2))
# # tong tat ca cac phan tu trong array
print(np.sum(arr1))
#tong cac hang
print(np.sum(arr1,axis =0))
#tong cac cot
print(np.sum(arr1,axis =1))

In [16]:
#broadcasting - cho phep numpy lam viec voi cac arr co shape khac nhau
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr1+arr2)
arr3 = np.empty_like(arr2) # tao mot mang arr3 co shape giong voi arr2

[[2 4 6]
 [4 6 8]
 [5 7 9]]
